project:
  type: website
  title: "State Space Model Workshop 2025, Livingstone, Zambia"
  execute-dir: project
  output-dir: docs
  render:
      - about.qmd
      - index.qmd
      - Module_1_Introduction.qmd
      - Module_2_Data.qmd
      - Module_3_Biomass_estimation.qmd
      - Module_4_Growth_model_Introduction.qmd
      - Module_5_RingWidth_only_model.qmd
      - Module_6_RingWidth_and_Census.qmd
      - Module_7_Comparing_Biomass_Estimates.qmd
      - Module_8_TR_and_Census_model_w_climate.qmd

website:
  title: "State Space Model Workshop 2025, Livingstone, Zambia"
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Kah5/State_space_workshop
  sidebar:
    style: "docked"
    search: true
    contents:
      - about.qmd
      - index.qmd
      - Module_1_Introduction.qmd
      - Module_2_Data.qmd
      - Module_3_Biomass_estimation.qmd
      - Module_4_RingWidth_only_model.qmd
      - Module_5_RingWidth_and_Census.qmd
      - Module_6_Comparing_Biomass_Estimates.qmd
      - Module_7_TR_and_Census_model_w_climate.qmd
  page-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: solar
    css: styles.css
    toc: true


callout-appearance: simple

date: today
date-format: iso

editor: visual

