---
title: "Additional Resources"
author: "Andria Dawson and Kelly Heilman"
format:
  html:
    code-fold: true
---

## **Videos**

-   The NEON [workshop videos on near-term ecological forecasting](https://youtube.com/playlist?list=PLLWiknuNGd500TE80k3MTfWMfFv20zHuf&si=pIOLo2AEL6vz_c07), including a session on [Bayesian Hierarchical Models](https://youtu.be/zoSk9_5ow3U?si=6BDd3KKakppJOga8). MEKE: based on the titles of the talks, I'd think the following would be most relevant for this workshop (in order): 1. Why forecast? 4. Bayesian Hierarchical Models. 6. State Space Models. 11. Fusing Data. 3. Characterizing Uncertainty. 8. Propagating Uncertainty. I personally plan to try to watch these. :-)

-   Chris Fonnesbeck. Tutorial and video by of 80-minute talk from PyData 2022 London. "Probabilistic Python: An Introduction to Bayesian Modeling with PyMC" <https://www.pymc.io/blog/chris_F_pydata2022.html>. Good intro and overview of Bayesian modeling, not super-focused on Python-specific implementation. 

-   Probabilistic Programming and Bayesian Methods for Hackers. <https://dataorigami.net/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/> "Introduction to Bayesian methods + probabilistic programming with a computation/understanding-first, mathematics-second point of view." 

-   Mike Dietze was teaching his Bayesian course back in spring 2020 when the COVID lockdown started. There are short videos for the second half of the course here:\
    <https://www.youtube.com/playlist?list=PLYbd7iIaRtNTfXLWI4a3lUp_gV61eD1jN>

## blog posts

-   This accessible [blog post](http://varianceexplained.org/r/empirical_bayes_baseball/) explaining one of the chief benefits of Bayesian inference, especially hierarchical modeling: it allows you to "borrow information" from other related sources, especially in a low sample size scenario. Robinson frames it in terms of successful at bats in baseball, but even if you don't understand baseball you can reframe it as "How many times x am I successful at something after n attempts." The question addressed: would you rather choose a baseball player who hits 4 / 10 successfully or hits 300 /1000 successfully. 

-   A related conceptual resource (not a blog\...I couldn't figure out what category to put this one in) is Rubin's 1981 "8 schools" example: there are eight parallel experiments in 8 schools testing the effect of SAT coaching. Each experiment yields an estimate for the effectiveness of the coaching. However, because the sample sizes varied, the associated standard errors varied as well, and thus the 8 estimates had differing precision. A hierarchical model in this case would allow you to combine information from all 8 schools into a single estimate of the overall effectiveness (a parameter mu), without assuming the schools are identical in their effectiveness (i.e. you have 8 different parameters theta of each school's effectiveness, where the theta's themselves come from a normal distribution with mean mu). Here is an [example](https://www.datascienceblog.net/post/machine-learning/probabilistic_programming/) calling stan from R to run the analysis. The conclusion was the overall effectiveness of the program wasn't a slam dunk as evidenced by the 95% posterior credible interval for mu that included 0 (Bayesian equivalent of a 95% confidence interval).

## books

-   Bayesian Models

-   : A Statistical Primer for Ecologists N. Thompson Hobbs and Mevin Hooten. <https://press.princeton.edu/books/hardcover/9780691159287/bayesian-models>Gelman et al., 2020.  Bayesian Workflow. <https://arxiv.org/abs/2011.01808>. More about process rather than content of Bayesian modeling rather than content.

-   Bayesian Data Analysis by Gelman et al., which can be a little dense, but is sort of the definitive practical resource for Bayesian statisticians and often used to teach Bayesian Statistics courses.

-   Ecological Forecasting. 2017. Mike Dietze. It\'s a great book, get a copy! So much in here that is useful and practical.

-   The Ecological Detective: confronting models with data. 1997. Hilborn and Mangel. This book is 25+ years olds but still a really good one. They do such a nice job of walking the reader through the spectrum of statistical approaches/philosophies of doing science...from frequentist to maximum likelihood inference to Bayesian inference.

-   Gelman and Hill. 2009

## vignettes/tutorials (software oriented)

-   NIMBLE and Stan both have great tutorials/examples/documentation on their respective websites. NIMBLE's examples are a little more geared to applications in Ecology, owing to the background of the creators.

-   examples using Jupyter notebooks:\
    PyMC: [https://www.pymc.io/projects/docs/en/stable/learn.html\
    ](https://www.pymc.io/projects/docs/en/stable/learn.html)Numpyro: [https://num.pyro.ai/en/latest/index.html#introductory-tutorials\
    ](https://num.pyro.ai/en/latest/index.html#introductory-tutorials)
