---
title: "Welcome and Schedule"
---

## Welcome to the Workshop: "Forest growth and carbon with uncertainty from tree-rings and census data"

This repository contains the material for the Workshop "Forest growth and carbon with uncertainty from tree-rings and census data" taught at World Dendro on Sunday, 27th July 2025.

## Objectives

In this workshop we will introduce and work with a Bayesian statistical modelling framework to:

1.  use tree-ring data to estimate annual tree diameter growth with uncertainty
2.  integrate tree-ring data with forest census data to estimate annual growth for all trees on the plot (i.e. those with and without tree ring data)
3.  show how this approach can directly link annual growth to climate and other drivers, and
4.  scale annual growth to carbon accumulation. 

We will work through examples developed in R and RStudio. Experience with R is helpful but not required. All are welcome.

## Schedule

|     Time      |                    Topic                    |      Presenter      |
|:-----------------:|:--------------------------------:|:-----------------:|
| 9:00 - 10:00  |           Module 1: Introduction            | Kelly, Andria, Ruby |
| 10:00 - 10:30 |     Module 2: Tree Ring and Census Data     |        Kelly        |
| 10:30 - 11:00 |        Module 3: Biomass Estimation         |        Kelly        |
| 11:00 - 11:15 |              Coffee/Tea break?              |                     |
| 11:15 - 12:00 |       Module 4: Tree ring only model        |       Andria        |
| 11:30 - 12:00 | Module 5: Tree ring and forest census model |       Andria        |
| 12:00 - 12:30 |    Module 6: Comparing Biomass Estimates    |    Andria/Kelly     |
| 12:30 - 1:30  |                    Lunch                    |                     |

## Two options for how to work through this workshop:

1.  No-code: Work though on this website
2.  Running .qmd files on Posit Cloud--.qmd files can be run similarly to rmarkdown files

Follow these [Instructions for getting started with this tutorial on POSIT cloud](https://docs.google.com/document/d/1K5ZSQT7rf6SouKSRQ0KpPjsGdl-d3WjMrmQ_Kxj66fw/edit?usp=sharing).
